### ISSUE TITLE
General improvements

### ISSUE THREAD

**Issue by rudlorenz** [Atlant154/cm_heat_equation_cpp#10]
## Style

  1. In my opinion, main.cpp should be at the top level of the project.
  2. Class fields should have an underscore at the end.
  3. Change the name of `tridiagonal_matrix` field `free` to a different name. (to avoid name collision) (or just put an underscore at the end, w/e)

## Code

  1. Const qualifiers for trivial types as function parameters are useless.
  2. Missing const qualifiers for member functions. Every member function, that doesn't change class fields should be marked `const`
  3. Macro defined constants instead of class members. (global variables are bad and macro defined globals are evil)

Also, I think, that instead of empty ctor and dtor in `tridiagonal_matrix` they should be marked as `default`. This way the compiler will mark default ctor and dtor as `constexpr`. 

```c++
    tridiagonal_matrix() = default;
    ~tridiagonal_matrix() = default;
```

**Comment by npatsakula** [comment]
I fixed it([commit](https://github.com/Atlant154/cm_heat_equation_cpp/commit/f6ab0ee13ba4b25978144604560464f572903c4d)). Thanks for the comments.
