### ISSUE TITLE
tridiagonal matrix class improvements

### ISSUE THREAD

**Issue by rudlorenz** [Atlant154/cm_heat_equation_cpp#14]
- [x]  fix field naming (add dash at the end).
- [x] fix get functions naming (remove dash at the end).
- [ ] fix ctor (all field initializing with member initializer list)

Clarifications on "fix ctor":
instead of 

```c++
tridiagonal_matrix::tridiagonal_matrix(unsigned int h_num, unsigned int time_layers_num) : 
h_num(h_num), time_layers_num(time_layers_num)
{
	this -> h = (x_right_bound - x_left_bound) / h_num;
	this -> tau = (time_right_bound - time_left_bound) / time_layers_num;
	above.reserve(h_num - 1);
	main.reserve(h_num);
	below.reserve(h_num - 1);
}
```

do this (assuming you fixed the names already)

```c++
tridiagonal_matrix::tridiagonal_matrix(unsigned int h_num, unsigned int time_layers_num) 
:  h_num_(h_num), 
   h_( (x_right_bound - x_left_bound) / h_num), 
   tau_(time_right_bound - time_left_bound) / time_layers_num), 
   above_(h_num - 1), 
   main_(h_num), 
   below_(h_num - 1)
{
}
```

**Comment by npatsakula** [comment]
> main_(h_num), 

Using this notation means use a vector as an array. In this case, we have problems with using the `vector.insert()` - it moves the end of the vector by the number in brackets. It is because of this problem that the `vector.reserve()` was used.
